
default: &default
  adapter: mysql2
  database:
  host: localhost
  username: root
  password: 11111
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: homework10


test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
